hl.on("hyprland.start", function()
    hl.exec_cmd("pgrep pipewire-pulse || pipewire-pulse &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store &")
    hl.exec_cmd("hyprpaper & waybar")
end)
